"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Role="principal"|"teacher"|"student";
type View="login"|"student"|"teacher"|"students"|"library"|"viewer";
type Status="assigned"|"draft"|"submitted"|"corrected"|"redo";
type Activity={id:string;title:string;category:string;description:string;status?:Status;progress?:number};
type QueueItem={id:string;student:string;activity:Activity;submittedAt:string};

const activities:Activity[]=[
  {id:"a31",title:"3.1 Je me renseigne pour un visa et des cours de français",category:"Écoute · A2",description:"16 pistes audio · annotation sur page",status:"draft",progress:40},
  {id:"a32",title:"3.2 Je m’inscris à l’école de langues",category:"Écoute · A2",description:"12 pistes audio · annotation sur page",status:"assigned",progress:0},
  {id:"a33",title:"3.3 Je comprends les horaires",category:"Écoute · A2",description:"8 pistes audio · annotation sur page",status:"corrected",progress:100},
  {id:"a34",title:"3.4 Je laisse un message vocal",category:"Production · A2",description:"10 pistes audio · production orale",status:"submitted",progress:100},
];

export default function Home(){
  const [role,setRole]=useState<Role|null>(null),[view,setView]=useState<View>("login"),[theme,setTheme]=useState<"chateau"|"nuit">("chateau"),[settings,setSettings]=useState(false),[solid,setSolid]=useState(false),[calm,setCalm]=useState(false),[fontSize,setFontSize]=useState(1),[toast,setToast]=useState("");
  const [queue,setQueue]=useState<QueueItem[]>([{id:"q1",student:"Amina",activity:activities[3],submittedAt:"hier · 16 h 40"},{id:"q2",student:"Carlos",activity:activities[0],submittedAt:"aujourd’hui · 9 h 12"}]);
  const [active,setActive]=useState<Activity>(activities[0]),[reviewing,setReviewing]=useState<QueueItem|null>(null),[from,setFrom]=useState<View>("student");
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2400)};
  const login=(next:Role)=>{setRole(next);setView(next==="student"?"student":"teacher");notify(next==="student"?"Bonjour Amina !":"Bonjour Claire !")};
  const open=(activity:Activity,source:View,review?:QueueItem)=>{setActive(activity);setFrom(source);setReviewing(review??null);setView("viewer")};
  const logout=()=>{setRole(null);setView("login");setSettings(false)};
  useEffect(()=>{document.documentElement.style.setProperty("--fs",["14.5px","16px","18px"][fontSize]);document.body.className=[theme==="nuit"?"nuit":"",solid?"solid":"",calm?"calm":""].filter(Boolean).join(" ")},[theme,solid,calm,fontSize]);
  return <>
    <div className="bg"><i className="blob b1"/><i className="blob b2"/><i className="blob b3"/><i className="blob b4"/></div>
    {view!=="login"&&<AppBar role={role!} view={view} go={setView} logout={logout} settings={()=>setSettings(v=>!v)}/>}
    {settings&&<Settings theme={theme} setTheme={setTheme} solid={solid} setSolid={setSolid} calm={calm} setCalm={setCalm} fontSize={fontSize} setFontSize={setFontSize}/>}
    <main className={view==="viewer"?"viewer-main":""}>
      {view==="login"&&<Login onLogin={login}/>}
      {view==="student"&&<StudentHome open={a=>open(a,"student")} activities={activities}/>}
      {view==="teacher"&&<TeacherHome queue={queue} open={q=>open(q.activity,"teacher",q)} go={setView}/>}
      {view==="students"&&<Students/>}
      {view==="library"&&<Library open={a=>open(a,"library")} assign={a=>notify(`« ${a.title} » a été assignée.`)}/>}
      {view==="viewer"&&<Viewer activity={active} review={reviewing} leave={()=>setView(from)} submit={()=>{notify("Travail envoyé à Claire ✓");setView("student")}} finish={redo=>{if(reviewing)setQueue(q=>q.filter(x=>x.id!==reviewing.id));notify(redo?`Renvoyé à ${reviewing?.student} — à refaire`:`Corrigé et renvoyé à ${reviewing?.student} ✓`);setView("teacher")}}/>}
    </main>
    <div className={`toast glass2 ${toast?"on":""}`} role="status">{toast}</div>
  </>;
}

function Wordmark(){return <div className="wordmark">Mon<b>French</b></div>}
function AppBar({role,view,go,logout,settings}:{role:Role;view:View;go:(v:View)=>void;logout:()=>void;settings:()=>void}){return <header className="app glass"><Wordmark/><span className="grow"/>{role!=="student"&&view!=="viewer"&&<nav className="seg" aria-label="Navigation principale"><button className={view==="teacher"?"on":""} onClick={()=>go("teacher")}>Accueil</button><button className={view==="students"?"on":""} onClick={()=>go("students")}>Élèves</button><button className={view==="library"?"on":""} onClick={()=>go("library")}>Bibliothèque</button></nav>}<button className="iconbtn" onClick={settings} aria-label="Réglages">⚙</button><button className="btn btn-ghost" onClick={logout}>Quitter</button></header>}

function Login({onLogin}:{onLogin:(r:Role)=>void}){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onLogin("student")};return <section className="login view on"><div className="login-card glass"><Wordmark/><p className="sub">Votre espace de français, simplement.</p><form onSubmit={submit}><label>Identifiant<input name="identifier" required autoComplete="username"/></label><label>Mot de passe<input name="password" type="password" required autoComplete="current-password"/></label><button className="btn btn-primary wide">Se connecter</button></form><div className="demo"><button className="btn" onClick={()=>onLogin("student")}>Démo élève</button><button className="btn" onClick={()=>onLogin("teacher")}>Démo enseignant</button></div><p className="tiny lock">Accès privé · Données protégées</p></div></section>}

function StudentHome({activities:items,open}:{activities:Activity[];open:(a:Activity)=>void}){const [pile,setPile]=useState<"todo"|"sent"|"done">("todo");const filtered=items.filter(a=>pile==="todo"?["assigned","draft","redo"].includes(a.status!):pile==="sent"?a.status==="submitted":a.status==="corrected");return <section className="view on"><div className="hero"><div><p className="sub">Bonjour Amina</p><h1>Mon travail</h1></div><span className="badge b">Groupe A</span></div><div className="glass card"><div className="pilltab"><button className={pile==="todo"?"on":""} onClick={()=>setPile("todo")}>À faire <span className="count">2</span></button><button className={pile==="sent"?"on":""} onClick={()=>setPile("sent")}>Envoyé <span className="count">1</span></button><button className={pile==="done"?"on":""} onClick={()=>setPile("done")}>Corrigé <span className="count">1</span></button></div>{filtered.map(a=><ActivityRow key={a.id} activity={a} onClick={()=>open(a)}/>)}</div></section>}
function ActivityRow({activity,onClick}:{activity:Activity;onClick:()=>void}){const labels:Record<Status,[string,string]>={assigned:["gy","À faire"],draft:["b","En cours"],submitted:["am","Envoyé"],corrected:["gr","Corrigé"],redo:["b","À refaire"]};const badge=labels[activity.status??"assigned"];return <button className="act" onClick={onClick}><span className="thumb">◉</span><span className="grow"><span className="tag">{activity.category}</span><strong>{activity.title}</strong><small>{activity.progress?`En cours · ${activity.progress} %`:activity.description}</small>{activity.progress?<span className="bar"><i style={{width:`${activity.progress}%`}}/></span>:null}</span><span className={`badge ${badge[0]}`}>{badge[1]}</span></button>}

function TeacherHome({queue,open,go}:{queue:QueueItem[];open:(q:QueueItem)=>void;go:(v:View)=>void}){return <section className="view on"><div className="hero"><div><p className="sub">Bonjour Claire</p><h1>Vue d’ensemble</h1></div><button className="btn btn-primary" onClick={()=>go("library")}>Assigner une activité</button></div><div className="grid g3 stats"><article className="glass card stat"><span className="n">{queue.length}</span><span className="sub">copies à corriger</span></article><article className="glass card stat"><span className="n">8</span><span className="sub">élèves actifs</span></article><article className="glass card stat"><span className="n">4</span><span className="sub">activités publiées</span></article></div><section className="glass card block"><div className="row"><div className="grow"><h2>À corriger</h2><p className="sub">{queue.length?`${queue.length} copies attendent votre correction.`:"Tout est corrigé. Belle journée !"}</p></div><span className="badge am">{queue.length}</span></div><hr/>{queue.map(q=><button className="act" key={q.id} onClick={()=>open(q)}><span className="thumb amber">✎</span><span className="grow"><strong>{q.student} · {q.activity.title}</strong><small>{q.submittedAt}</small></span><span className="btn">Corriger</span></button>)}</section></section>}

function Students(){const students=["Amina","Carlos","Mei","Yusuf","Sofia","Pavel","Fatou","Jin"];return <section className="view on"><div className="hero"><div><p className="sub">Administration simple</p><h1>Élèves</h1></div><button className="btn btn-primary">Nouvel élève</button></div><div className="grid g2">{students.map((name,i)=><article className="glass card row" key={name}><span className="avatar">{name[0]}</span><span className="grow"><strong>{name}</strong><small>Groupe {i<4?"A":"B"} · actif</small></span><button className="btn btn-ghost">•••</button></article>)}</div></section>}

function Library({open,assign}:{open:(a:Activity)=>void;assign:(a:Activity)=>void}){return <section className="view on"><div className="hero"><div><p className="sub">Activités disponibles</p><h1>Bibliothèque</h1></div><button className="btn btn-primary">Importer une activité</button></div><div className="glass card"><div className="row filters"><input aria-label="Rechercher" placeholder="Rechercher une activité…"/><button className="btn">Toutes les catégories</button></div><hr/>{activities.map(a=><div className="act" key={a.id}><span className="thumb">◉</span><span className="grow"><span className="tag">{a.category}</span><strong>{a.title}</strong><small>{a.description}</small></span><button className="btn" onClick={()=>open(a)}>Aperçu</button><button className="btn btn-primary" onClick={()=>assign(a)}>Assigner</button></div>)}</div></section>}

function Viewer({activity,review,leave,submit,finish}:{activity:Activity;review:QueueItem|null;leave:()=>void;submit:()=>void;finish:(redo:boolean)=>void}){
  const [tool,setTool]=useState("read"),[saved,setSaved]=useState(true),[answer,setAnswer]=useState(""),[choice,setChoice]=useState(0),[confirm,setConfirm]=useState(false);const timer=useRef<number|undefined>(undefined);
  const dirty=()=>{setSaved(false);window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setSaved(true),850)};
  useEffect(()=>{const handler=(event:MessageEvent)=>{if(event.source!==document.querySelector("iframe" )?.contentWindow)return;if(!event.data||typeof event.data!=="object"||typeof event.data.type!=="string")return;if(event.data.type==="monfrench-save")dirty()};window.addEventListener("message",handler);return()=>window.removeEventListener("message",handler)},[]);
  return <section className="view on"><div className="viewerbar glass2"><button className="btn btn-ghost" onClick={leave}>← Retour</button><span className="ttl grow">{review?`Copie de ${review.student} · `:""}{activity.title}</span><span className={`save ${saved?"":"busy"}`}><i/>{saved?"Enregistré":"Enregistrement…"}</span>{!review&&<button className="btn btn-primary" onClick={()=>setConfirm(true)}>Soumettre</button>}</div><div className="stage"><div className="tools glass2" aria-label="Outils d’annotation">{[["read","↖"],["pen","✎"],["hl","▰"],["eraser","⌫"]].map(([id,label])=><button key={id} className={tool===id?"on":""} onClick={()=>setTool(id)} aria-label={id}>{label}</button>)}<i/><button onClick={dirty} aria-label="Annuler">↶</button></div><article className="page"><header className="pagehead"><div><span className="tag">{activity.category}</span><h2>{activity.title}</h2></div><strong>MonFrench</strong></header><p className="consigne">Écoutez la piste, puis complétez les réponses. Votre travail est enregistré automatiquement.</p><div className="audio"><button>◀</button><button className="play">▶</button><button>▶</button><span className="grow"><b>Piste 3 · 16</b><i><em style={{width:"34%"}}/></i></span><small>0:24 / 1:12</small></div><div className="exercise"><h3>1. Complétez le dialogue.</h3><p>— Bonjour, je voudrais <input value={answer} onChange={e=>{setAnswer(e.target.value);dirty()}} aria-label="Réponse 1"/> pour suivre des cours de français.</p><p>— Bien sûr. Vous avez déjà <input aria-label="Réponse 2" onChange={dirty}/> ?</p><h3>2. Choisissez la bonne réponse.</h3>{["Elle demande un visa.","Elle cherche une école de langues.","Elle réserve un hôtel."].map((text,i)=><button className={`choice ${choice===i?"sel":""}`} key={text} onClick={()=>{setChoice(i);dirty()}}><i>{choice===i?"✓":""}</i>{text}</button>)}</div><span className="pageno">1 / 4</span></article>{review&&<div className="reviewbar glass2"><textarea placeholder="Écrire une note pour l’élève…"/><button className="btn" onClick={()=>finish(true)}>À refaire</button><button className="btn btn-primary" onClick={()=>finish(false)}>Terminer la correction</button></div>}</div>{confirm&&<div className="overlay"><div className="modal glass"><h2>Soumettre ce travail ?</h2><p className="sub">Après l’envoi, vous ne pourrez plus le modifier sauf si votre professeur le retourne « À refaire ».</p><div className="row end"><button className="btn btn-ghost" onClick={()=>setConfirm(false)}>Pas encore</button><button className="btn btn-primary" onClick={submit}>Soumettre</button></div></div></div>}</section>;
}

function Settings({theme,setTheme,solid,setSolid,calm,setCalm,fontSize,setFontSize}:{theme:"chateau"|"nuit";setTheme:(x:"chateau"|"nuit")=>void;solid:boolean;setSolid:(x:boolean)=>void;calm:boolean;setCalm:(x:boolean)=>void;fontSize:number;setFontSize:(x:number)=>void}){return <aside className="settings glass2"><h3>Réglages</h3><label>Thème<span className="seg"><button className={theme==="chateau"?"on":""} onClick={()=>setTheme("chateau")}>Château de verre</button><button className={theme==="nuit"?"on":""} onClick={()=>setTheme("nuit")}>Nuit parisienne</button></span></label><label>Taille du texte<span className="step"><button onClick={()=>setFontSize(Math.max(0,fontSize-1))}>−</button><b>{["S","M","L"][fontSize]}</b><button onClick={()=>setFontSize(Math.min(2,fontSize+1))}>+</button></span></label><label>Contraste uni<input type="checkbox" checked={solid} onChange={e=>setSolid(e.target.checked)}/></label><label>Réduire les animations<input type="checkbox" checked={calm} onChange={e=>setCalm(e.target.checked)}/></label></aside>}
